Traceback (most recent call last):
  File "/homes/ahb24/MSc_Topology_Codebase/entailment_surfaces/phdim_clustering_validation_best_metrics.py", line 483, in <module>
    main()
  File "/homes/ahb24/MSc_Topology_Codebase/entailment_surfaces/phdim_clustering_validation_best_metrics.py", line 477, in main
    results = statistical_validator.run_statistical_validation()
  File "/homes/ahb24/MSc_Topology_Codebase/entailment_surfaces/phdim_clustering_validation_best_metrics.py", line 357, in run_statistical_validation
    self._save_statistical_results(validation_results)
  File "/homes/ahb24/MSc_Topology_Codebase/entailment_surfaces/phdim_clustering_validation_best_metrics.py", line 391, in _save_statistical_results
    json.dump(serializable_results, f, indent=2, default=convert_numpy_types)
NameError: name 'serializable_results' is not defined
